version: 2
updates:
  # GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      timezone: Europe/Zurich
      time: "01:30"
    labels:
      - dependencies/github-actions
  # npm
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: sunday
      timezone: Europe/Zurich
      time: "03:00"
    labels:
      - dependencies/npmjs
